services:
  - type: web
    name: journal-app
    env: java
    plan: free
    rootDir: .
    buildCommand: "./mvnw clean install"
    startCommand: "./mvnw spring-boot:run"
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: SPRING_DATA_MONGODB_DATABASE
        sync: false
