spring:
  profiles:
    active: dev

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: ${WEATHER_API_KEY}
