spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /journal

weather:
  api:
    key: ${WEATHER_API_KEY}
