weather:
  api:
    key: ${WEATHER_API_KEY}
  main:
    allow-circular-references: true
  server:
    port: ${SERVER_PORT}
    servlet:
      context-path: /journal

  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true
